version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"      
      - "15672:15672"    

  server:
    build:
      context: ./api/backend/server
      dockerfile: Dockerfile  
    depends_on:
      - rabbitmq
    restart: unless-stopped  

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile 
    depends_on:
      - rabbitmq
    ports:
      - "8000:8000"          
    restart: unless-stopped 